name: MinigamesCore
version: ${project.version}
main: dev.thedutchruben.core.minigamescore
api-version: 1.13
commands:
  game:
    description: Game command
    permission: minigames.core.command.game